
services:
  db:
    image: postgres:15
    container_name: umchool_db
    restart: always
    environment:
      POSTGRES_USER: ****
      POSTGRES_PASSWORD: *****
      POSTGRES_DB: umschoolkz
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: umschool_api
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:port/umschoolkz

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: umschool_bot
    restart: always
    depends_on:
      - api
    environment:
      API_URL: ***
      BOT_TOKEN: "***"

volumes:
  postgres_data:
